# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [ ]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [2]:
# Import torch
import torch

# Create random tensor
tensor = torch.rand(size=(7, 7))
tensor

tensor([[0.1568, 0.8429, 0.3792, 0.8824, 0.0246, 0.0822, 0.7302],
        [0.9878, 0.5092, 0.0708, 0.2141, 0.7803, 0.9675, 0.2339],
        [0.4249, 0.3423, 0.7042, 0.9987, 0.1273, 0.2455, 0.0018],
        [0.4430, 0.3977, 0.5806, 0.8297, 0.0221, 0.6215, 0.6854],
        [0.6823, 0.6936, 0.3558, 0.9757, 0.3305, 0.9221, 0.5203],
        [0.7439, 0.7875, 0.9955, 0.9201, 0.9062, 0.0759, 0.7378],
        [0.8195, 0.8503, 0.6567, 0.4427, 0.5444, 0.5621, 0.5326]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [3]:
# Create another random tensor
ano_tensor = torch.rand(size=(1, 7))
# Perform matrix multiplication
result = torch.mul(tensor, ano_tensor.T)
result.shape

torch.Size([7, 7])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [6]:
# Set manual seed
torch.manual_seed(0)

# Create two random tensors
tensor1 = torch.rand(size=(7, 7))
tensor2 = torch.rand(size=(1, 7))

# Matrix multiply tensors
result2 = tensor1 @ torch.transpose(tensor2, dim0=0, dim1=-1)
result2, result2.shape

(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]),
 torch.Size([7, 1]))

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [7]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [22]:
# Set random seed
torch.cuda.manual_seed(1234)

# Check for access to GPU
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(device)
# Create two random tensors on GPU
tensor3 = torch.rand(size=(2, 3), device=device)
tensor4 = torch.rand(size=(2, 3), device=device)
tensor3.shape, tensor4.shape

cpu


(torch.Size([2, 3]), torch.Size([2, 3]))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [26]:
# Perform matmul on tensor_A and tensor_B
result3 = tensor3 @ tensor4.T
result3

tensor([[0.3893, 0.5810],
        [0.3343, 0.5781]])

### 8. Find the maximum and minimum values of the output of 7.

In [27]:
# Find max
Max = torch.max(result3).item()
# Find min
Min = torch.min(result3).item()
Max, Min

(0.5810213685035706, 0.33425837755203247)

### 9. Find the maximum and minimum index values of the output of 7.

In [28]:
# Find arg max

argMax = torch.argmax(result3).item()
# Find arg min
argMin = torch.argmin(result3).item()
argMax, argMin


(1, 2)


### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [29]:
# Set seed
torch.manual_seed(7)

# Create random tensor
tensor5 = torch.rand(size=(1, 1, 1, 10))

# Remove single dimensions
squeezed_tensor5 = tensor5.squeeze()

# Print out tensors and their shapes
print(tensor5, tensor5.shape)
print(squeezed_tensor5, squeezed_tensor5.shape)

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
